# --- COMMON SETTINGS ---
x-lsiodefaults: &lsio-defaults # Define a reusable template
  restart: unless-stopped
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Amsterdam

services:
  # --- INDEXER MANAGER ---
  prowlarr:
    <<: *lsio-defaults # Use the reusable template
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    volumes:
      - ./config/prowlarr:/config
    ports:
      - 9696:9696

  # --- MEDIA SERVER ---
  jellyfin:
    <<: *lsio-defaults # Use the reusable template
    image: lscr.io/linuxserver/jellyfin:latest # Changed to LSIO for better QSV driver support
    container_name: jellyfin
    volumes:
      - ./config/jellyfin:/config
      - ./StreamingData:/data  # Your movie folder
    devices:
      - /dev/dri:/dev/dri      # CRITICAL: This enables hardware acceleration for the CPU
    ports:
      - 8096:8096

  jellyseerr:
    <<: *lsio-defaults # Use the reusable template
    image: lscr.io/linuxserver/jellyseerr:latest # Changed to LSIO to support PUID/PGID
    container_name: jellyseerr
    volumes:
      - ./config/jellyseerr:/config
    ports:
      - 5055:5055

  # --- SERVARR STACK ---
  radarr:
    <<: *lsio-defaults # Use the reusable template
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - ./config/radarr:/config
      - ./StreamingData:/data
    ports:
      - 7878:7878

  sonarr:
    <<: *lsio-defaults # Use the reusable template
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - ./config/sonarr:/config
      - ./StreamingData:/data
    ports:
      - 8989:8989

  bazarr:
    <<: *lsio-defaults # Use the reusable template
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    volumes:
      - ./config/bazarr:/config
      - ./StreamingData:/data
    ports:
      - 6767:6767

  nzbget:
    <<: *lsio-defaults # Use the reusable template
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    volumes:
      - ./config/nzbget:/config
      - ./StreamingData:/data
    ports:
      - 6789:6789